buying/views/store.py
import re
from typing_extensions import Self
from flask import Flask, request, template_rendered, Blueprint
from flask import url_for, redirect, flash
from flask import render_template
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
from numpy import identity, product
import random, string
from sqlalchemy import null
from link import *
import math
from base64 import b64encode
from api.sql import Member, Orders, Product, Record, Cart, Transaction, Comments

productStore = Blueprint('productStore', __name__, template_folder='../templates')

@productStore.route('/', methods=['GET', 'POST'])
@login_required
def product():
    result = Product.count_all(current_user.id)
    count = math.ceil(result[0]/9)
    flag = 0
    
    if 'keyword' in request.args and 'page' in request.args:
        total = 0
        single = 1
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        keyword = request.values.get('keyword')
        
        products = Product.get_product_by_keyword(keyword, current_user.id)
        product_list = []
        final_data = []
        
        for product in products:
            curr_product = {
                'pNo': product[0],
                'pName': product[1],
                'price': product[2],
                'launcherId': product[4],
                'username': product[5]
            }
            product_list.append(curr_product)
            total = total + 1

        
        if(len(product_list) < end):
            end = len(product_list)
            flag = 1
            
        for j in range(start, end):
            final_data.append(product_list[j])
            
        count = math.ceil(total/9)
        
        return render_template('productStore.html', single=single, keyword=keyword, product_data=product_list, user=current_user.name, page=page, flag=flag, count=count)    

    
    elif 'pNo' in request.args:
        pNo = request.args['pNo']
        product = Product.get_product_by_pNo(pNo)
        image = 'sdg.jpg'
        
        product = {
            'pNo': product[0],
            'pName': product[1],
            'price': product[2],
            'description': product[3],
            'launcherId': product[4],
            'username': product[5],
            'image': image
        }

        comment_list = []
        comments = Comments.get_product_comments(pNo)
        for comment in comments:
            curr_comment = {
                'username': comment[1],
                'commentTime' : comment[2],
                'comment' : comment[3]
            }
            comment_list.append(curr_comment)

        return render_template('product.html', product_data = product, comment_list = comment_list, user=current_user.name)
    
    elif 'page' in request.args:
        total = 0
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        
        products = Product.get_all_product(current_user.id)
        product_list = []
        final_data = []
        
        for product in products:
            product = {
                'pNo': product[0],
                'pName': product[1],
                'price': product[2],
                'launcherId': product[4],
                'username': product[5]
            }
            product_list.append(product)
            total += 1
            
        if(len(product_list) < end):
            end = len(product_list)
            flag = 1
            
        for j in range(start, end):
            final_data.append(product_list[j])
        count = math.ceil(total/9)    

        return render_template('productStore.html', product_data=final_data, user=current_user.name, page=page, flag=flag, count=count)    
    
    elif 'keyword' in request.args:
        single = 1
        keyword = request.values.get('keyword')
        Product.get_product_by_keyword(keyword, current_user.id)
        products = cursor.fetchall()
        product_list = []
        total = 0
        
        for product in products:
            curr_product = {
                'pNo': product[0],
                'pName': product[1],
                'price': product[2],
                'launcherId': product[4],
                'username': product[5]
            }
            product_list.append(curr_product)
            total = total + 1
            
        if(len(product_list) < 9):
            flag = 1
        
        count = math.ceil(total/9)    
        
        return render_template('productStore.html', keyword=keyword, single=single, product_data=product_list, user=current_user.name, page=1, flag=flag, count=count)    
    
    else:
        products = Product.get_all_product(current_user.id)
        product_list = []
        total = 0
        for product in products:
            curr_product = {
                'pNo': product[0],
                'pName': product[1],
                'price': product[2],
                'launcherId': product[4],
                'username': product[5]
            }
            total += 1
            if len(product_list) < 9:
                product_list.append(curr_product)
        count = math.ceil(total/9)
        
        return render_template('productStore.html', product_data=product_list, user=current_user.name, page=1, flag=flag, count=count)

@productStore.route('/cart', methods=['GET', 'POST'])
@login_required
def cart():
    if request.method == 'POST':
        if "pNo" in request.form :
            cart = Cart.get_current_cart(current_user.id)
            if(cart == None):
                time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                format = 'yyyy-mm-dd hh24:mi:ss'
                Cart.add_cart(current_user.id, time, format)
                cart = Cart.get_current_cart(current_user.id) 

            products = Cart.get_all_product_in_cart(cart[0], cart[1])
            pNo = request.values.get('pNo')

            exist = False
            for product in products:
                if str(product[0]) == pNo:
                    Orders.update_order_increment_pNo(cart[0], cart[1], pNo)
                    exist = True
                    break
            
            if not exist:
                Orders.add_order(cart[0], cart[1], pNo, 1)

        elif "delete" in request.form :
            pNo = request.values.get('delete')
            cart = Cart.get_current_cart(current_user.id)
            Orders.delete_order(cart[0], cart[1], pNo)
        
        elif "user_edit" in request.form:
            change_order()  
            return redirect(url_for('productStore.product'))
        
        elif "buy" in request.form:
            change_order()
            if request.values.get('paymentMethod') == 0 or request.values.get('deliveryType') == 0:
                return redirect(url_for('productStore.cart'))
            
            return redirect(url_for('productStore.transacting', paymentMethod=request.values.get('paymentMethod'), deliveryType = request.values.get('deliveryType')))

        elif "order" in request.form:
            cart = Cart.get_current_cart(current_user.id)
            products = Cart.get_all_product_in_cart(cart[0], cart[1])

            time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            format = 'yyyy-mm-dd hh24:mi:ss'

            deliveryFee = int(request.values.get('deliveryFee'))
            deliveryType = request.values.get('deliveryType')
            paymentMethod = request.values.get('paymentMethod')


            tNo = Transaction.add_transaction(cart[0], time, format, paymentMethod, deliveryType, deliveryFee)
            for product in products:
                Record.add_record(tNo, product[0], product[2], product[3])
            
            Cart.complete_cart(cart[0], cart[1], tNo)

            return render_template('complete.html', user=current_user.name)

    cart = Cart.get_current_cart(current_user.id)
    if cart == None:
        return render_template('empty.html', user=current_user.name)

    products = Cart.get_all_product_in_cart(cart[0], cart[1])
    product_list = []
    for product in products:
        pNo = product[0]
        pName = product[1]
        amount = product[2]
        price = product[3]
        
        curr_product = {
            'pNo': pNo,
            'pName': pName,
            'amount': amount,
            'price': price
        }
        product_list.append(curr_product)
    
    if len(product_list) == 0:
        return render_template('empty.html', user=current_user.name)
    else:
        return render_template('cart.html', product_data=product_list, user=current_user.name)

@productStore.route('/transacting')
@login_required
def transacting():
    cart = Cart.get_current_cart(current_user.id)
    products = Cart.get_all_product_in_cart(cart[0], cart[1])
    product_list = []

    for product in products:
        curr_product = {
            'pNo': product[0],
            'pName': product[1],
            'amount': product[2],
            'price': product[3]
        }
        product_list.append(curr_product)
    

    deliveryType = request.values.get('deliveryType')
    paymentMethod = request.values.get('paymentMethod')

    paymentMethod = "信用卡" if paymentMethod == "1" else "貨到付款"
    deliveryType = "宅配" if deliveryType == "1" else "超商取貨"
    deliveryFee = 100 if deliveryType == '1' else 50
    product_price = Cart.get_total_price(cart[0], cart[1])
    total_price = product_price + deliveryFee
    return render_template('transacting.html', product_data=product_list,product_price=product_price, total_price=total_price, user=current_user.name, deliveryFee=deliveryFee, deliveryType=deliveryType, paymentMethod=paymentMethod)

@productStore.route('/transactionlist')
@login_required
def transactionList():
    transactions = Transaction.get_transact_list_by_buyer(current_user.id)
    transaction_list = []

    for transaction in transactions:

buying/templates/cart.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>
<div class="container-xl">
  <br/>
  <form method="post" action={{ url_for('productStore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
        <th><center>商品操作</center></th>
      </tr>
      {% for product in product_data %}
      <tr>
        <td> <center>{{ product.pNo }}</center></td>
        <td> <center>{{ product.pName }}</center></td>
        <td> <center>{{ product.price }}</center></td>
        <td width="20%">
          <center>
            <input class="form-control" type="number" onkeyup="value=value.replace(/[^\d]/g,'')" min="1" value="{{ product.amount }}" name="{{ product.pNo }}">

          </center>
        </td>
        <td>
          <center>
            <button class="btn btn-danger" type="submit" value="{{ product.pNo }}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ product.pName }}\' 嗎？'))">
              刪除
            </button>
          </center>
      </td>
      </tr>
      {% endfor %}
    </table>

    <center>
      <select class="form-select mb-2" aria-label="Default select example" name="paymentMethod">
        <option value="0" selected>付款方式</option>
        <option value="1">信用卡</option>
        <option value="2">貨到付款</option>
      </select>

      <select class="form-select mb-2" aria-label="Default select example" name="deliveryType">
        <option value="0" selected>運送方式</option>
        <option value="1">宅配</option>
        <option value="2">超商</option>
      </select>      

      <div class="option">
        <button class="btn btn-primary" type="submit" value="edit" name="user_edit" >繼續購物</button>
        <button class="btn btn-success" type="submit" value="edit" name="buy" >直接結帳</button>
      </div>
    </center>


  </form>

</div>

{% endblock content%}

buying/templates/complete.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 下單完成 {% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="30%" height="30%" src="../static/img/order_success.png">
  </center>
  <center>
    <h4>下單完成！</h4>
  </center>
  <center>
    
      <a href="{{ url_for('productStore.product') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          回書店
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

buying/templates/empty.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="50%" height="50%" src="../static/img/empty_cart.png">
  </center>
  <center>
    
      <a href="{{ url_for('productStore.product') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          繼續購物
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

buying/templates/frontstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;拍賣中心</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.product') }}">商品導覽</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.cart') }}">購物車</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.transactionList') }}">歷史訂單</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.transactionManager') }}">我的賣場</a>
                    </li>
                </ul>

                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>

                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <a href="{{ url_for('manager.productManager') }}" style='text-decoration:none'><li style="color:white;list-style-type:none">使用者 : {{user}}</li></a>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

buying/templates/product.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}Product{% endblock title%}

{% block content %}

{% set temp = 'img/' + product_data.image %}

<br/>
<div class="row">
  <div class="card" style="width: 20rem;margin-left:5%">
    <img src={{ url_for('static', filename = temp  ) }} class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ product_data.pName }}</h5>
      <p class="card-text"></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><b>商品單價</b>&nbsp;&nbsp;{{ product_data.price }}</li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a class="card-text text-decoration-none" href="{{ url_for('chat.chatroom', mId=product_data.launcherId)}}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-messenger mt-2 mb-2" viewBox="0 0 16 16" href="x">
            <path d="M0 7.76C0 3.301 3.493 0 8 0s8 3.301 8 7.76-3.493 7.76-8 7.76c-.81 0-1.586-.107-2.316-.307a.639.639 0 0 0-.427.03l-1.588.702a.64.64 0 0 1-.898-.566l-.044-1.423a.639.639 0 0 0-.215-.456C.956 12.108 0 10.092 0 7.76zm5.546-1.459-2.35 3.728c-.225.358.214.761.551.506l2.525-1.916a.48.48 0 0 1 .578-.002l1.869 1.402a1.2 1.2 0 0 0 1.735-.32l2.35-3.728c.226-.358-.214-.761-.551-.506L9.728 7.381a.48.48 0 0 1-.578.002L7.281 5.98a1.2 1.2 0 0 0-1.735.32z"/>
          </svg>
          {{product_data.username}}
        </a>
      </li>
    </ul>
    <div class="card-body">
      <a href="{{ url_for('productStore.product') }}" class="btn btn-outline-primary">回商品列表</a>
    </div>
  </div>


  <div class="col-sm-6">
    <form method="post" action={{ url_for('productStore.cart') }}>
      <div class="card" style="margin-top:10%">
        <h5 class="card-header">商品介紹</h5>
        <div class="card-body">
          <p class="card-text">
            {{product_data.description}}
          </p>
          <button class="btn btn-outline-success" type="submit" value="{{product_data.pNo}}" name="pNo">加入購物車</a>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-md-8 col-lg-6">
    <div class="card shadow-0 border" style="background-color: #f0f2f5;">
      <div class="card-body p-4">
        
        <div class="mb-4">
          <form method="post" action={{ url_for('productStore.comment') }}>
            <div class="form-group">
              <textarea class="form-control" id="comment" name="comment" rows="4" placeholder="Type your comment..."></textarea>
              <input class="d-none" name="pNo" value="{{product_data.pNo}}">
              <div class="d-flex justify-content-end mt-2">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>

        {% for comment in comment_list %}
          <div class="card mb-4">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(32).webp" alt="avatar" width="25"
                    height="25" />
                  <p class="small">{{comment.username}}</p>
                </div>
              </div>
              <div style="white-space: pre-wrap;">{{comment.comment}}</div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>
</div>


{% endblock content%}

buying/templates/productStore.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}商品列表{% endblock title%}

{% block content%}
<br/>

{% with messages = get_flashed_messages() %}
{% if messages %}
  
<script language="javascript">

  alert('您沒有管理員的權限喔！');

</script>

{% endif %}
{% endwith %}

<div class="book_table container-xxl">

  <form class="d-flex col-sm-4" action="{{ url_for('productStore.product', keyword=1) }}">
    <div class="input-group">
    <span class="input-group-text" id="basic-addon1">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </span>
    <input name='keyword' class="form-control me-2" type="search" placeholder="搜尋商品" aria-label="Search">
    </div>
  </form><br/>
  <form method="post" action={{ url_for('productStore.cart') }}>
      
      
      {% for product in product_data %}
      {% if loop.index % 3 == 1 %}
      <div class="row">
      {% endif %}
      
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{product.pName}}</h5>
              <div class="card-text" style="text-decoration: none;">${{product.price}}</div>
              <a href="{{ url_for('productStore.product', pNo=product.pNo) }}" class="btn btn-outline-primary">查看商品資訊</a>
              <button class="btn btn-outline-success" type="submit" value="{{product.pNo}}" name="pNo" >加入購物車</button>
            </div>
          </div>
        </div>

        {% if loop.index % 3 == 0 %}
        </div><br/>
        {% endif %}
            
      {% endfor %}
    </table>
  </form>


  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('productStore.product', page=page-1) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      {% for i in range(1, count+1) %}
      {% if single == 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for('productStore.product', keyword=keyword, page=i) }}">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{{ url_for('productStore.product', page=i) }}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if flag == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('productStore.product', page=page+1) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>



</div>

{% endblock content%}

buying/templates/transacting.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}ProductStore{% endblock title%}

{% block content%}
<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('productStore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
      </tr>
      {% for product in product_data %}
      <tr>
        <td> <center>{{ product.pNo }}</center></td>
        <td> <center>{{ product.pName }}</center></td>
        <td> <center>{{ product.price }}</center></td>
        <td width="20%">
          <center>
            {{ product.amount }}
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="col align-self-end">
      
    </div>




    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-start">
          <b class="ml-50">付款方式: {{ paymentMethod }}</b>
        </div>
      </div>
    </div>

    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-start">
          <b class="ml-50">運送方式: {{ deliveryType }}</b>
        </div>
      </div>
    </div>

    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-end">
          <b class="ml-50">商品總價 : {{ product_price }}元</b>
        </div>
      </div>
    </div>

    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-end">
          <b class="ml-50">運費 : {{ deliveryFee }}元</b>
        </div>
      </div>
    </div>


    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-end">
          <b class="ml-50">訂單總價：{{ total_price }} 元</b>
        </div>
      </div>
    </div>
    <input type="hidden" name="deliveryFee" value="{{deliveryFee}}">
    <input type="hidden" name="deliveryType" value="{{deliveryType}}">
    <input type="hidden" name="paymentMethod" value="{{paymentMethod}}">
    
    <center> 
      <div class="option">
        <a href="{{ url_for('productStore.cart') }}"><button class="btn btn-primary" type="submit" >回購物車</button></a>
        <button class="btn btn-success" type="submit" value="order" name="order">下訂單</button>
    </div>
    </center>

  </form>
</div>
{% endblock content%}

buying/templates/transactionList.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}ProductStore{% endblock title%}

{% block content %}
<!-- <form method="post" action="#"> -->
  {% for transaction in transaction_data %}
  <div class="modal fade" id="staticBackdrop{{transaction.tNo}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">訂單細項列表</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <div class="mb-3">
                    <table class="table table-bordered">
                      <tr>
                        <th><center>商品名稱</center></th>
                        <th><center>商品單價</center></th>
                        <th><center>訂購數量</center></th>
                      </tr>
                      
                      {% for detail in detail_data %}
                      {% if detail.tNo == transaction.tNo %}
                      <tr>
                        <td> <center>{{ detail.pName }}</center></td>
                        <td> <center>{{ detail.salePrice }}</center></td>
                        <td> <center>{{ detail.amount }}</center></td>
                      </tr>
                      {% endif %}
                      {% endfor %}
                    </table>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal" style="width:30%;">回訂單</button>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
<!-- </form> -->



<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('productStore.transactionList') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>訂單編號</center></th>
        <th><center>訂單總價</center></th>
        <th><center>訂單時間</center></th>
        <th><center>查看訂單</center></th>
      </tr>
      {% for transaction in transaction_data %}
      <tr>
        <td> <center>{{ transaction.tNo }}</center></td>
        <td> <center>{{ transaction.total_price }}</center></td>
        <td> <center>{{ transaction.transTime }}</center></td>
        <td width="20%">
          <center>
            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{transaction.tNo}}">
              查看訂單細項
            </button>
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>

  </form>
</div>

{% endblock content %}