selling/views/analysis.py
from flask import render_template, Blueprint
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import Analysis
import datetime


analysis = Blueprint('analysis', __name__, template_folder='../templates')

@analysis.route('/dashboard')
@login_required
def dashboard():
    revenue_list = []
    transaction_count_list = []
    for month in range(1,13):
        monthly_revenue = Analysis.monthly_revenue(current_user.id, datetime.date.today().strftime("%Y"), month)

        if not monthly_revenue:
            revenue_list.append(0)
        else:
            revenue_list.append(monthly_revenue[0])
        
        monthly_transaction_count = Analysis.monthly_transaction_count(current_user.id, datetime.date.today().strftime("%Y"), month)
        if not monthly_transaction_count:
            transaction_count_list.append(0)
        else:
            transaction_count_list.append(monthly_transaction_count[0])
    


    username_list = []
    member_sale_list = []
    member_sale_count_list = []
    member_sales = Analysis.member_sale(current_user.id, datetime.date.today().strftime("%Y"))
    for member_sale in member_sales:
        username_list.append(member_sale[1])
        member_sale_list.append(member_sale[2])
        member_sale_count_list.append(member_sale[3])
    
    print(username_list)
    print(member_sale_list)
    print(member_sale_count_list)

    return render_template('dashboard.html', revenue_list = revenue_list, transaction_count = transaction_count_list, member_sale_list = member_sale_list, username_list = username_list, member_sale_count_list = member_sale_count_list, user=current_user.name)

selling/views/manager.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import *
import imp, random, os, string
from werkzeug.utils import secure_filename
from flask import current_app

UPLOAD_FOLDER = 'static/product'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

manager = Blueprint('manager', __name__, template_folder='../templates')

def config():
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    config = current_app.config['UPLOAD_FOLDER'] 
    return config

@manager.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return redirect(url_for('manager.productManager'))

@manager.route('/productManager', methods=['GET', 'POST'])
@login_required
def productManager():        
    if 'delete' in request.values:
        pNo = request.values.get('delete')
        product = Product.get_product_by_pNo(pNo)
        print(type(current_user.id))
        print(current_user.id)
        print(type(product[4]))
        print(product[4])
        print(pNo == product[4])
        if(product == None or str(product[4]) != current_user.id):
            flash('failed')
        else:
            Product.discontinue_product(pNo)
            flash(f'successfully discontinue product {product[1]}')
    
    elif 'edit' in request.values:
        pNo = request.values.get('edit')
        return redirect(url_for('manager.edit', pNo=pNo))
    
    product_data = get_product_by_memberId(current_user.id)
    return render_template('productManager.html', product_data = product_data, user=current_user.name)

def get_product_by_memberId(mId):
    products = Product.get_product_by_launcher(mId)
    product_data = []
    for i in products:
        product = {
            'pNo': i[0],
            'pName': i[1],
            'price': i[2],
        }
        product_data.append(product)
    return product_data

@manager.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        name = request.values.get('name')
        price = request.values.get('price')
        description = request.values.get('description')
        launchBy = current_user.id

        if (len(name) < 1 or len(price) < 1):
            return redirect(url_for('manager.productManager'))
        
        Product.add_product(
            {
                'pName' : name,
                'price' : price,
                'description': description,
                'launchBy' : launchBy
            }
        )

        return redirect(url_for('manager.productManager'))

    return render_template('productManager.html')

@manager.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    if request.method == 'POST':
        Product.update_product(
            {
                'pNo': request.values.get('pNo'),
                'pName': request.values.get('pName'),
                'price': request.values.get('price'),
                'description': request.values.get('description'),
            }
        )
        
        return redirect(url_for('manager.productManager'))
    else:
        product = show_info()
        return render_template('edit.html', data=product)

def show_info():
    pNo = request.args['pNo']
    data = Product.get_product_by_pNo(pNo)
    pName = data[1]
    price = data[2]
    description = data[3]
    isAvailable = data[4]
    product = {
        'pNo': pNo,
        'pName': pName,
        'price': price,
        'description': description,
        'isAvailable': isAvailable
    }
    return product


@manager.route('/transactionManager', methods=['GET', 'POST'])
@login_required
def transactionManager():
    transactions = Transaction.get_transact_list_by_seller(current_user.id)
    transaction_list = []
    for transaction in transactions:
        curr_transact = {
            'tNo': transaction[0],
            'buyerId': transaction[1],
            'total_price': transaction[2],
            'transTime': transaction[3]
        }
        transaction_list.append(curr_transact)
        
    transactDetails = Transaction.get_transact_detail_by_seller(current_user.id)
    detail_list = []

    for detail in transactDetails:
        curr_detial = {
            'tNo': detail[0],
            'pName': detail[2],
            'amount': detail[3],
            'salePrice': detail[4]
        }
        detail_list.append(curr_detial)

    return render_template('transactionManager.html', transaction_data = transaction_list, detail_data = detail_list, user=current_user.name)

selling/templates/backstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.1.2/echarts.min.js" integrity="sha512-ppWbHq6q2f7HAwS481w6qikuC0XEeBnmkRg6KWnWg3zSIbJwWWBgsCDMAxzSB7SVqXzWwSYQ2s8TSJKjnaikMg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }
    
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand">&nbsp;我的賣場</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.productManager') }}">商品管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.transactionManager') }}">訂單管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('analysis.dashboard') }}">資料分析</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.product') }}">商品導覽</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('chat.chatroom') }}">我的聊天室</a>
                    </li>
                </ul>



                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                    <li style="color:white;list-style-type:none">使用者 : {{user}}</li>
                </ul>
                <div class="d-flex">
                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
                </div>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

selling/templates/dashboard.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block title %}後台資料分析{% endblock title%}
{% block content %}

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <!-- Dashboard -->
  <div id="dashboard">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">訂單數量分析</button>

        <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">消費總額排名</button>        
      </div>      
    </nav>
  </div>
  <br/>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <center> 
        <div id="maina" style="width:1200px;height:500px;border-style:dashed;"></div>
      </center>
    </div>

    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <center>
        <div id="mainc" class="container-fluid" style="width:1200px;height:500px;border-style:dashed;"></div>
      </center>
    </div>
  </div>
</div>

<script>

  // 以長條圖與折線圖分析各月訂單
  var myCharta = echarts.init(document.getElementById('maina'));
  var revenue = {{ revenue_list | tojson }};
  var count = {{ transaction_count | tojson }};
  var optiona = {
    title: {
      text: '各月訂單數量分析'
    },
    tooltip: {},
    legend: {
      data: ['訂單數量']
    },
    xAxis: {
      data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
    },
    yAxis: {},
    series: [{
      name: '銷售總額',
      type: 'bar',
      symbolSize: 16,
      data: revenue,
      markPoint: {
        data: [
          {type: 'max', name: '銷量最高月份'},
          {type: 'min', name: '銷量最低月份'}
        ]
      },
      label: {
        show: true,
        position: 'top',
        textStyle: {
          fontSize: 15
        }
      }
    }
    ],
    legend: {
      show: true
    },
  };
  myCharta.setOption(optiona);

  // 使用動態長條圖查看消費總額最多的使用者
  var myChartc = echarts.init(document.getElementById('mainc'));
  var member_sale_list = {{ member_sale_list | tojson }};
  var username_list = {{ username_list | tojson }};
  var member_sale_count_list = {{ member_sale_count_list | tojson }};
  var optionc = {
    title: {
      text: '使用者消費排名'
    },
    xAxis: {
      type: 'value'
    },
    yAxis: {
      type: 'category',
      data: username_list,
      inverse: true,
      animationDuration: 300,
      animationDurationUpdate: 300,
      max: 3
    },
    tooltip: {},
    series: [
      {
        name: '消費總額',
        type: 'bar',
        data: member_sale_list,
      },
      {
        name: '訂單總數',
        type: 'bar',
        data: member_sale_count_list,
      }
      ],
    legend: {
      show: true
    },
    animationDuration: 3000,
    animationDurationUpdate: 3000,
    animationEasing: 'linear',
    animationEasingUpdate: 'linear'
  };
  myChartc.setOption(optionc);

  setTimeout(function() {
    run();
  }, 0);
        
  setInterval(function() {
    update();
  }, 3000);
      
</script>

{% endblock content %}

selling/templates/edit.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}

{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}


<br/>
<div class="container-xl">
  <br/>
  <form method="post" enctype=multipart/form-data action={{ url_for('manager.edit') }}>
    <table class="table table-bordered">
      <tr>
        <th>商品編號</th>
        <td><input class="form-control" type="text" value="{{ data.pNo }}" name="pNo" readonly class="id_input"></td>
      </tr>
      <tr>
        <th>商品名稱</th>
        <td><input class="form-control" type="text" value="{{ data.pName }}" name="pName" required></td>
      </tr>
      <tr>
        <th>單價</th>
        <td><input class="form-control" type="text" value="{{ data.price }}" name="price" required></td>
      </tr>
      <tr>
        <th>商品敘述</th>
        <td>
          <textarea class="form-control" name="description">{{ data.description }}</textarea>
        </td>
      </tr>
      <!-- <tr>
        <th>狀態</th>
        <td>
          <select class="form-control" name="isAvailable">
            {% if data.isAvailable == 1 %}
              <option value="1" selected>上架中</option>
              <option value="0">下架中</option>
            {% elif data.isAvailable == 0 %}
              <option value="1" >上架中</option>
              <option value="0" selected>下架中</option>
            {% endif %}
        </select>
      </tr> -->
      <!-- <tr>
        <th>商品圖片</th>
        <td>
          <input type="file" name="file" id="file-uploader" data-target="file-uploader"/>
        </td>
      </tr> -->
    </table>
    <center>
      <div class="option">
        <button class="btn btn-outline-success" type="submit">確定修改</button> 
        <a href="{{ url_for('manager.productManager') }}"><button class="btn btn-outline-danger">回商品管理</button></a>
      </div>
    </center>

  </form>
</div>



{% endblock content%}

selling/templates/manager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<div class="btn_div">
  <h1 class="book_title left">31 Lab Book Store</h1>
  <a href="{{ url_for('analysis.dashboard') }}"  title="資料分析"><img class="cart" src="{{ url_for('static', filename='./img/dashboard.png') }}"></a>
  <a href="{{ url_for('logout') }}"  title="登出"><img class="logout" src="{{ url_for('static', filename='./img/logout.png') }}"></a>
</div>
<div class="btn_div">
  <p class="welcome">歡迎 , 管理者：{{user}}</p>
</div>
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>

{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'faild' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<div class="book_table">
  <form method='post' action={{ url_for('manager') }} >
    <table cellpadding="10" border='3'>
      <tr>
        <th>商品編號</th>
        <th>商品名稱</th>
        <th>商品售價</th>
        <th>商品類別</th>
        <th></th>
        <th></th>
      </tr>
      {% for book in book_data %}
      <tr>
        <td> {{ book.pNo }}</td>
        <td> {{ book.pName }}</td>
        <td> {{ book.price }}</td>
        <td>
          <button type="submit" value="{{book.pNo}}" name="edit">修改
          </button>
        </td>
        <td>
          <button type="submit" value="{{book.pNo}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ book.pName }}\' 嗎？'))">
            刪除
          </button>
        </td>
      </tr>
      {% endfor %}
    </table>
      <div class="book_table">
        <a href={{ url_for('add')}}><button value="new" name="new" type="button"> 上架新商品</button></a>
      </div>
    </form>

</div>

{% endblock content%}

selling/templates/productManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 商品管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>


{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<script>
    $(document).ready(function(){
        $("#keyword").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
&nbsp;
&nbsp;
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋商品" aria-label="Search">
    </div>
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        新增商品
    </button>
</div>

<form method="post" enctype=multipart/form-data action={{ url_for('manager.add') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增商品</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputProductName" class="form-label">商品名稱</label>
                        <input type="text" class="form-control" id="inputProductName" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputUnitPrice" class="form-label">商品單價</label>
                        <input type="number" class="form-control" id="inputUnitPrice" name="price" required>
                    </div>

                    <div class="mb-3">
                        <label for="inputProductDesc" class="form-label">商品敘述</label>
                        <textarea class="form-control" id="inputProductDesc" name="description" required></textarea>
                    </div>
                    <!-- <div class="mb-3">
                        <label for="inputProductImg" class="form-label">商品圖片</label><br/>
                        <input type="file" name="file" id="file-uploader" data-target="file-uploader" required/>
                    </div> -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br/>

<div class="container-xxl">

<form method='post' action={{ url_for('manager.productManager') }} >
<table id="manager" class="table table-bordered">
    <thead>
        <tr>
            <th width="10%"><center>商品編號</center></th>
            <th width="20%"><center>商品名稱</center></th>
            <th width="15%"><center>商品單價</center></th>
            <th colspan="2"><center>資料操作</center></th>
        </tr>
    </thead>
    <tbody id="product">
    {% for i in product_data %}
        <tr>
            <td><center>{{ i.pNo }}</center></td>
            <td><center>{{ i.pName }}</center></td>
            <td><center>{{ i.price }}</center></td>
            <td><center><button type="submit" value="{{i.pNo}}" name="edit" class="btn btn-success">編輯商品</button></center></td>
            <td><center><button type="submit" value="{{i.pNo}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ i.pName }}\' 嗎？'))" class="btn btn-danger">刪除商品</button></center></td>
        </tr>
    {% endfor %}
    </tbody>
    
</table>
</form>


</div>

<script>
    function have_product(){
      alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}

selling/templates/transactionManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}
<!-- website title -->
{% block title %} 訂單管理 {% endblock title %}

{% block content %}
<!-- website content -->

<script>
    $(document).ready(function(){
        $("#keyword").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#orderlist tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

{% for transaction in transaction_data %}
<div class="modal fade" id="staticBackdrop{{transaction.tNo}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">訂單細項列表</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <table class="table table-bordered">
                        <tr>
                            <th><center>商品名稱</center></th>
                            <th><center>商品單價</center></th>
                            <th><center>訂購數量</center></th>
                        </tr>
                        {% for detail in detail_data %}
                        {% if detail.tNo == transaction.tNo %}
                        <tr>
                            <td> <center>{{ detail.pName }}</center></td>
                            <td> <center>{{ detail.salePrice }}</center></td>
                            <td> <center>{{ detail.amount }}</center></td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal" style="width:30%;">回訂單</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<br/>
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋訂單" aria-label="Search">
    </div>
</div>

<br/>

<div class="container-xxl">
<table class="table table-bordered">
    <thead>
        <tr>
            <!-- <th width="10%">商品編號</th> -->
            <th width="15%"><center>單號</center></th>
            <th width="15%"><center>訂購人</center></th>
            <th width="15%"><center>訂單總價</center></th>
            <th width="25%"><center>訂單時間</center></th>
            <th><center>訂單操作</center></th>
        </tr>
    </thead>
    <tbody id="orderlist">
    {% for transaction in transaction_data %}
        <tr>
            <td><center>{{ transaction.tNo }}</center></td>
            <td><center>{{ transaction.buyerId }}</center></td>
            <td><center>{{ transaction.total_price }}</center></td>
            <td><center>{{ transaction.transTime }}</center></td>
            <td><center>
                <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{transaction.tNo}}">
                    查看訂單細項
                </button>
            </center></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}