chat/views/chatting.py
import re
from typing_extensions import Self
from flask import Flask, request, template_rendered, Blueprint
from flask import url_for, redirect, flash
from flask import render_template
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
from numpy import identity, product
import random, string
from sqlalchemy import null
from link import *
import math
from base64 import b64encode
from api.sql import Member, Orders, Product, Record, Cart, Transaction, Comments, Chat

chat = Blueprint('chat', __name__, template_folder='../templates')

@chat.route('/', methods=['GET', 'POST'])
@login_required
def chatroom():
    chatroom_list = []
    
    current_chatroomId = None
    message_list = []
    receiver = None
    sender = None

    if request.method == 'POST':
        current_chatroomId = request.values.get('chatroomId')
        Chat.add_message_to_chatroom(current_chatroomId, current_user.id, request.values.get('message'), datetime.now())

    
    if request.values.get('mId') != None:
        receiverId = request.values.get('mId')
        current_chatroom = Chat.get_chatroom(current_user.id, receiverId)
        if not current_chatroom:
            time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            format = 'yyyy-mm-dd hh24:mi:ss'
            current_chatroomId = Chat.create_chatroom(current_user.id, receiverId, time, format)
        else:
            current_chatroomId = current_chatroom[0]


        messages = Chat.get_chatroom_messages(current_chatroomId)
        for message in messages:
            curr_message = {
                'senderId': message[1],
                'content': message[2],
                'messageTime': message[3]
            }
            message_list.append(curr_message)


        receiver_items = Member.get_member_by_Id(receiverId)
        receiver = {
            'receiverId': receiver_items[0],
            'account': receiver_items[1],
            'username': receiver_items[2]
        }

        sender_items = Member.get_member_by_Id(current_user.id)
        sender = {
            'senderId': sender_items[0],
            'account': sender_items[1],
            'username': sender_items[2]
        }


    chatrooms = Chat.select_user_all_chatroom(current_user.id)
    for chatroom in chatrooms:
        curr_chatroom = {
            'chatroomId': chatroom[0],
            'receiverId': chatroom[1],
            'receiverName': chatroom[2]
        }
        chatroom_list.append(curr_chatroom)


    return render_template('chatroom.html', current_chatroomId = current_chatroomId, receiver = receiver, sender = sender, chatroom_list=chatroom_list, message_list = message_list)

chat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    body {
        background-color: #74EBD5;
        background-image: linear-gradient(90deg, #74EBD5 0%, #9FACE6 100%);
      
        min-height: 100vh;
      }
      
      ::-webkit-scrollbar {
        width: 5px;
      }
      
      ::-webkit-scrollbar-track {
        width: 5px;
        background: #f5f5f5;
      }
      
      ::-webkit-scrollbar-thumb {
        width: 1em;
        background-color: #ddd;
        outline: 1px solid slategrey;
        border-radius: 1rem;
      }
      
      .text-small {
        font-size: 0.9rem;
      }
      
      .messages-box,
      .chat-box {
        height: 510px;
        overflow-y: scroll;
      }
      
      .rounded-lg {
        border-radius: 0.5rem;
      }
      
      input::placeholder {
        font-size: 0.9rem;
        color: #999;
      }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;拍賣中心</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.product') }}">商品導覽</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.cart') }}">購物車</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('productStore.transactionList') }}">歷史訂單</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.transactionManager') }}">我的賣場</a>
                    </li>
                </ul>

                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>

                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <a href="{{ url_for('manager.productManager') }}" style='text-decoration:none'><li style="color:white;list-style-type:none">使用者 : {{user}}</li></a>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

chat/templates/chatroom.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}

{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}


<br/>

<div class="container py-5 px-4" >
  
    <div class="row rounded-lg overflow-hidden shadow" style="height: 800px;">
        <!-- Users box-->
        <div class="col-5 px-0 overflow-auto h-100">
            <div class="bg-white">
  
                <div class="bg-gray px-4 py-2 bg-light">
                    <p class="h5 mb-0 py-1">Recent</p>
                </div>
  
                <div class="messages-box">
                    <div class="list-group rounded-0">
                        {% for chatroom in chatroom_list %}
                            {% if chatroom.chatroomId == current_chatroomId %}
                                <a class="list-group-item list-group-item-action active text-white rounded-0">
                                    <div class="media"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                                        <div class="media-body ml-4">
                                            <div class="d-flex align-items-center justify-content-between mb-1">
                                                <h6 class="mb-0"> {{ chatroom.receiverName }}</h6>
                                                <!-- <small class="small font-weight-bold">25 Dec</small> -->
                                            </div>
                                            <!-- <p class="font-italic mb-0 text-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p> -->
                                        </div>
                                    </div>
                                </a>
                            {% else %}
                                <a href="{{ url_for('chat.chatroom', mId=chatroom.receiverId) }}" class="list-group-item list-group-item-action list-group-item-light rounded-0">
                                    <div class="media"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                                        <div class="media-body ml-4">
                                            <div class="d-flex align-items-center justify-content-between mb-1">
                                                <h6 class="mb-0">{{ chatroom.receiverName }}</h6>
                                                <!-- <small class="small font-weight-bold">14 Dec</small> -->
                                            </div>
                                            <!-- <p class="font-italic text-muted mb-0 text-small">Lorem ipsum dolor sit amet, consectetur. incididunt ut labore.</p> -->
                                        </div>
                                    </div>
                                </a>
                            {% endif %}
                        {% endfor%}
                    </div>
                </div>
            </div>
        </div>

        <!-- Chat Box-->
        <div class="col-7 px-0 h-100">
            {% if current_chatroomId != None %}
            <div class="px-4 py-5 chat-box bg-white overflow-auto" style="height: 90%;">
                {% for message in message_list %}
                    {% if message.senderId == sender.senderId %}
                        <!-- Sender Message-->
                        <div class="media w-50 mb-3">
                            <img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle mb-2">
                            <div class="media-body ml-3">
                                <div class="bg-light rounded py-2 px-3 mb-2">
                                    <p class="text-small mb-0 text-muted" style="white-space: pre-wrap;">
                                        {{ message.content }}
                                    </p>
                                </div>
                                <p class="small text-muted">
                                    {{ message.messageTime.strftime("%Y-%m-%d %H:%M:%S") }}
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <!-- Reciever Message-->
                        <div class="media w-50 ml-auto mb-3">
                            <img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle mb-2">
                            <div class="media-body">
                                <div class="bg-primary rounded py-2 px-3 mb-2">
                                    <p class="text-small mb-0 text-white " style="white-space: pre-wrap;">
                                        {{ message.content }}
                                    </p>
                                </div>
                                <p class="small text-muted">
                                    {{ message.messageTime.strftime("%Y-%m-%d %H:%M:%S") }}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
  
            <!-- Typing area -->
            <form method="post" action={{ url_for('chat.chatroom') }} class="bg-light" style="height: 10%;">
                <div class="input-group">
                    <input type="text" placeholder="Type a message" aria-describedby="button-addon2" class="form-control rounded-0 border-0 py-4 bg-light" name="message">
                    <input class="d-none" name="mId" value="{{ receiver.receiverId }}">
                    <input class="d-none" name="chatroomId" value="{{ current_chatroomId }}">
                    <div class="input-group-append">
                        <button id="button-addon2" type="submit" class="btn btn-link w-100 h-100"> 
                            <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 512 512" class="w-100 h-100"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M498.1 5.6c10.1 7 15.4 19.1 13.5 31.2l-64 416c-1.5 9.7-7.4 18.2-16 23s-18.9 5.4-28 1.6L284 427.7l-68.5 74.1c-8.9 9.7-22.9 12.9-35.2 8.1S160 493.2 160 480V396.4c0-4 1.5-7.8 4.2-10.7L331.8 202.8c5.8-6.3 5.6-16-.4-22s-15.7-6.4-22-.7L106 360.8 17.7 316.6C7.1 311.3 .3 300.7 0 288.9s5.9-22.8 16.1-28.7l448-256c10.7-6.1 23.9-5.5 34 1.4z"/></svg>                
                        </button>
                    </div>
                </div>
            </form>
            {% endif%}
        </div>

    </div>
</div>



{% endblock content%}